### ISSUE TITLE
Containerize The CDJ.

### ISSUE THREAD

**Issue by hiyaryan** [hiyaryan/the-cdj#150]
Use docker to containerize the project. 

Mirror the server running on Canonical, Ubuntu, 22.04 LTS, amd64 jammy image build on 2023-12-07.

See GitHub Copilot plugin to generate Docker assets. [Docker for GitHub Copilot](https://github.com/marketplace/docker-for-github-copilot). Might simplify containerizing the project.

**Comment by davidzlu** [comment]
Even though the application is running in containers, seeding the DB still needs to happen on docker host after installing backend project. 
  - Need to change seed.js to use env var url, not hardcoded localhost url. Without code change, must install project and run from host
  - seed.js currently needs modern JS support, Mongoose, joi, and some other things installed already before the seed scripts can run.
  - Would be nice to simplify the seeding scripts so that they don't depend on backend code and other libraries at all, i.e. no imports
